//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Balder;
        ///using Balder.Math;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl
        ///{
        ///	public class BusinessObject
        ///	{
        ///		private Coordinate _position;
        ///		public Coordinate Position
        ///		{
        ///			get { return _position; }
        ///			set { _position = value; }
        ///		}
        ///
        ///		public Color Color { get; set; }
        ///
        ///		public bool IsVisible { get; set; }
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string BusinessObject_cs {
            get {
                return ResourceManager.GetString("BusinessObject_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl.Content&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///    xmlns:Controls=&quot;clr-namespace:Balder.Controls;assembly=Balder&quot; 
        ///    xmlns:Geometries=&quot;clr-namespace:Balder.Objects.Geometries;assembly=Balder&quot; 
        ///    xmlns:local=&quot;clr-namespace:Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl&quot; 
        ///    xmlns:View=&quot;clr-namespace:Balder.View;ass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content_xaml {
            get {
                return ResourceManager.GetString("Content_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl
        ///{
        ///	public partial class Content
        ///	{
        ///		public Content()
        ///		{
        ///			InitializeComponent();
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Content_xaml_cs {
            get {
                return ResourceManager.GetString("Content_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Balder.Execution;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl
        ///{
        ///	public class MyGame : Game
        ///	{
        ///		public override void OnInitialize()
        ///		{
        ///			ContentManager.AssetsRoot = &quot;Samples/Data/ItemsControl/Assets&quot;;
        ///
        ///			base.OnInitialize();
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string MyGame_cs {
            get {
                return ResourceManager.GetString("MyGame_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Windows.Input;
        ///using Balder.Math;
        ///using Balder.MVVM;
        ///
        ///namespace Balder.Silverlight.SampleBrowser.Samples.Data.NodesControl
        ///{
        ///	public class ViewModel : INotifyPropertyChanged
        ///	{
        ///		public event PropertyChangedEventHandler PropertyChanged = (s, e) =&gt; { };
        ///
        ///		public ViewModel()
        ///		{
        ///			ManyObjects = new ObservableCollection&lt;BusinessObject&gt;();
        ///			FewObjects = new ObservableCollection&lt;BusinessObject&gt;();
        ///
        ///			Populate(Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewModel_cs {
            get {
                return ResourceManager.GetString("ViewModel_cs", resourceCulture);
            }
        }
    }
}
